### ISSUE TITLE
Where is cliphist storing all clipboard logs/from where it fetch those clipboard logs?

### ISSUE THREAD

**Issue by Greatz08** [sentriz/cliphist#101]
i couldnt find info on this so please guide.

**Comment by sentriz** [comment]
hi, the database is in `$XDG_CACHE_HOME/cliphist/db`

**Comment by Greatz08** [comment]
~/.cache/cliphist/db is universal/better way btw as many might not have XDG_CACHE_HOME env variable set to point home directory like in my case so just adding this point here for anyone who face issue with this command - XDG_CACHE_HOME/cliphist/db 
Thanks for the help tho :-))
