### ISSUE TITLE
how do I copy cliphist items to clipboard?

### ISSUE THREAD

**Issue by LaptopDev** [sentriz/cliphist#102]
the arch wiki says this utility supports multimedia

how do you copy out from cliphist cliphist items to clipboard via ID ?

Can someone explain to me what type of items can be copied and stored correctly to clipboard and what items are not supported? 

I am trying to use cliphist with bemenu to set my clipboard to a previous cliphist image item by processing the matched item selected from the piped cliphist list, but need to understand what processing is necessary to add it to my clipboard from its ID.

**Comment by sentriz** [comment]
hi, have you seen the `decode` command mentioned in readme? https://github.com/sentriz/cliphist?tab=readme-ov-file#select-old-item
