### ISSUE TITLE
Set clipboard database location

### ISSUE THREAD

**Issue by emmatebibyte** [sentriz/cliphist#103]
If there is a way to do this, I cannot find it. Otherwise, it would be highly useful to me to be able to do this.

**Comment by sentriz** [comment]
hi there,
yes after [v0.6.1](https://github.com/sentriz/cliphist/pull/89) is released, you can either

`$ cliphist -db-path /xyz <cmd>`

or 

`$ env CLIPHIST_DB_PATH=/xyz cliphist <cmd>`

or 

`$ cliphist -config-path conf <cmd>`

with conf looking like:

```
db-path /xyz
```

also: flags, env vars, and config file options are the same thing. so you could set the config-path with CLIPHIST_CONFIG_PATH

a full config could be

```
db-path /xyz
preview-width 100
max-items 100
```

see https://github.com/sentriz/flagconf/ for more info :+1:
