### ISSUE TITLE
xwayland support 

### ISSUE THREAD

**Issue by shadowe1ite** [sentriz/cliphist#106]
Is it possible to copy from an Xwayland application? I have been trying to copy from VSCode, but it's not working.

**Comment by sentriz** [comment]
hi, this is unrelated to cliphist. you need to see if wl-clipboard is working first

**Comment by shadowe1ite** [comment]
> hi, this is unrelated to cliphist. you need to see if wl-clipboard is working first

`wl-paste --type text --watch clipman store` is  working

`wl-paste --type text --watch cliphist store` not working

**Comment by sentriz** [comment]
how about 

wl-paste --type text --watch cat

does that output anything ?

**Comment by shadowe1ite** [comment]
> wl-paste --type text --watch cat

yes
![Tuesday_28_2024_18_53_59_PM](https://github.com/sentriz/cliphist/assets/54718375/4fd69a01-89ad-4e13-ba40-fad4f060cac2)

**Comment by sentriz** [comment]
and `echo hi | cliphist store` works?

**Comment by shadowe1ite** [comment]
> and `echo hi | cliphist store` works?

![image](https://github.com/sentriz/cliphist/assets/54718375/06e5b1fe-d53e-4a96-8037-ffee85d4fd87)


this command is used to store the value into clipbord history right ?
if yes its working

**Comment by sentriz** [comment]
not sure what's going on then. if `wl-paste --watch <cmd>` works, and `echo hi | <cmd>` works, when the issue is not with `<cmd>` it's with wl-paste

**Comment by shadowe1ite** [comment]
> not sure what's going on then. if `wl-paste --watch <cmd>` works, and `echo hi | <cmd>` works, when the issue is not with `<cmd>` it's with wl-paste

oh ok thanks

**Comment by sertchan** [comment]
https://github.com/hyprwm/Hyprland/issues/6725

issue related with hyprland see the thread
