### ISSUE TITLE
feature request: have an option to set an static history

### ISSUE THREAD

**Issue by ogabriel** [sentriz/cliphist#109]
It would be nice to have an option to set a file with a static history of things that I wanna copy on the future.

This would be useful for when you have big commands that you forget everytime, but the nature of the current `db` file does not allow to insert normal text there.

[Greenclip](https://github.com/erebe/greenclip) has that feature, but it does not play nice with wayland.

Thanks for the great clipboard manager!

**Comment by sentriz** [comment]
looks like dupe https://github.com/sentriz/cliphist/issues/23 wdyt?
