### ISSUE TITLE
No history when launching from sway

### ISSUE THREAD

**Issue by ghost** [sentriz/cliphist#110]
Hi,

First of all, thank you for making cliphist. 

I have added the following to my `~/.config/sway/config` file:

```
exec wl-paste --watch cliphist store

set $clip cliphist list | rofi -dmenu -P "Clipboard" | cliphist decode | wl-copy

bindsym $mod+c exec $clip
```

This successfully shows rofi, but without clipboard items. If I launch these commands from the terminal, it works. I am unsure of how to proceed with this issue and am thankful for any help.

**Comment by sentriz** [comment]
hm, can sway read XDG_CACHE_HOME? what does `$ swaymsg 'exec notify-send dir: $XDG_CACHE_HOME'` do? (single quotes so your shell doesnt interpret the env var)

**Comment by sentriz** [comment]
oh, we had this before. looks like dupe #67. please reopen or let me know if not :+1:
