### ISSUE TITLE
Paste item directly after select

### ISSUE THREAD

**Issue by bingo084** [sentriz/cliphist#111]
I use command below as picker.

```bash
cliphist list | rofi -dmenu | cliphist decode | wl-copy
```

After select an item, I have to use `ctrl-v` paste it again, is there anyway paste item directly after select?

I tried command below but not working.

```bash
cliphist list | rofi -dmenu | cliphist decode | wl-copy && wl-paste
```

**Comment by idIing** [comment]
`cliphist list | rofi -dmenu | cliphist decode | wl-copy && wtype $(wl-paste)`

be sure to install wtype

**Comment by bingo084** [comment]
> `cliphist list | rofi -dmenu | cliphist decode | wl-copy && wtype $(wl-paste)`
> 
> be sure to install wtype

Thanks, but I found that this only works for text, not images.

I simulated the shortcut key for paste.

```bash
cliphist list | rofi -dmenu | cliphist decode | wl-copy && wtype -M ctrl -k v -m ctrl
```

**Comment by sentriz** [comment]
thanks for the help @diagonalized 

can this be closed now @bingo084 ?

**Comment by mberrueta** [comment]
this more or less works, but the problem is that if you have a character like `-S` it fail wtype and nothing is pasted.

try `pacman -S xdg-desktop-portal-hyprland` for example

I solved with

`cliphist list | wofi -dmenu | cliphist decode | wl-copy && wl-paste --no-newline | xargs -I {} wtype {}`

**Comment by sentriz** [comment]
> if you have a character like -S it fail wtype and nothing is pasted

you probably need a `--` to discern flags from arguments. eg `wtype -- -S` will type `-S`

**Comment by thatanjan** [comment]
Thank you @bingo084 🙏🙏
Even Gemini couldn't give me a working solution.
