### ISSUE TITLE
One-click paste from selection

### ISSUE THREAD

**Issue by elefthei** [sentriz/cliphist#115]
Thanks for this great tool! 
I am trying to change the keybinding for paste so that I can paste in one step instead of two.

Now
1. Keybinding (SUPER+V) opens rofi/wofi for selection, confirm selection -> wl-clipboard
2. Normal paste (Ctrl + V) from wl-clipboard -> current window

Intended
1. Keybinding (SUPER+V) opens rofi/wofi for selection, confirm selection -> current window

I tried the following keybinding for SUPER+V but it's not working, I suspect because by opening rofi/wofi we lost the focused window to paste on (or it pastes to wofi before it closes).

`bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy | wl-paste`

**Comment by sentriz** [comment]
wl-copy or wl-paste will never do the paste action. They just manage the current clipboard. Maybe try something like wtype?

**Comment by sentriz** [comment]
seems like there's some info here 👍 https://github.com/sentriz/cliphist/issues/111
