### ISSUE TITLE
Looking for clipboard db at /cliphist

### ISSUE THREAD

**Issue by arilebedey** [sentriz/cliphist#122]
Kernel: Linux 6.11.3-arch1-1
OS: Arch Linux
Installation: Pacman
Cliphist: 0.6.0-1
Cliphist DB: ~/.cache/cliphist/db

Command: ❯ cliphist list | rofi -dmenu | cliphist decode | wl-copy
Log:
opening db: create cache dir: mkdir /cliphist: permission denied
extracting id: input not prefixed with id

After downgrade to 0.5.0-1, cliphist behaves normally and command shows clipboard history.

**Comment by sentriz** [comment]
dupe #120 , you need to upgrade to 0.6.1, it should be available in arch already
