### ISSUE TITLE
mkdir /cliphist  permission denied 

### ISSUE THREAD

**Issue by CarloCattano** [sentriz/cliphist#123]
I got this error message since a few days, and I'm not really sure whats the cause of it.
I dont get the clipboard stored as usual anymore

```bash 
wl-paste --watch cliphist store       
opening db: create cache dir: mkdir /cliphist: permission denied
```

**Comment by CarloCattano** [comment]
```open config file: open /cliphist/config: permission denied```

**Comment by sentriz** [comment]
dupe #120 , you need to update to 0.6.1
