### ISSUE TITLE
no | wofi except in terminal and 'extracting id: input not prefixed with id'

### ISSUE THREAD

**Issue by 100espressos** [sentriz/cliphist#125]
Search found someone else with this issue:
https://github.com/sentriz/cliphist/issues/120#issuecomment-2416178139

Here on arch with 0.6.1-1, 
`cliphist list | wofi --dmenu | cliphist decode | wl-copy`
does nothing in labwc.

It works in terminal but also outputs 'extracting id: input not prefixed with id'.
_edit_: This seems to happen if nothing is selected, and not relevant.

The cache is being created and used properly.

**Comment by sentriz** [comment]
what is the output of 

cliphist list

and the output of

cliphist list | wofi --dmenu

?

**Comment by 100espressos** [comment]
In console:

```
$ cliphist list          
4	cliphist list | wofi --dmenu ?
3	and the output of
2	cliphist list
1	what is the output of
```

`$ cliphist list | wofi --dmenu`
shows the menu as expected.

**Comment by sentriz** [comment]
what about `printf "%d\ttest\n" 4 | cliphist decode`

(4 is the id in the list)

**Comment by 100espressos** [comment]
With `test` on clipboard, that produces `test%` (% in inverse color).

**Comment by 100espressos** [comment]
I gather that zsh outputs '%' if the script ends without a newline, but it should not affect things.

**Comment by 100espressos** [comment]
Issue closed? I may check back sometime in the future, thanks.

**Comment by sentriz** [comment]
does the item get copied to your clipboard?

**Comment by 100espressos** [comment]
Yes, with `| wl-copy`, it seems things work correctly from a terminal,
but not with labwc shortcut command, so it seems reasonable for me to look in that direction now, if you excuse my red herring.

Thanks for your help and a great clipboard manager!

**Comment by 100espressos** [comment]
For posterity: It works to simply execute these as a single command or script, like `sh -c 'command | command'`
