### ISSUE TITLE
select old item "rofi"

### ISSUE THREAD

**Issue by Mathew-D** [sentriz/cliphist#15]
I was wondering if you had any idea how I could use rofi instead of dmenu for selection items.

**Comment by sentriz** [comment]
hi !! IIRC rofi has a `--dmenu` option that makes it's CLI interface behave like dmenu but not sure

**Comment by Mathew-D** [comment]
> hi !! IIRC rofi has a `--dmenu` option that makes it's CLI interface behave like dmenu but not sure

Thank you I found it a few minutes after I asked.  BTW Great job on the software.

**Comment by sentriz** [comment]
thanks :)

**Comment by kohane27** [comment]
Thank you for creating such an awesome program! Been looking for a clipboard manager that supports images.

For anyone wondering the full command with the flag, it's `cliphist list | rofi -dmenu | cliphist decode | wl-copy`.

To be extra clear, add the following to `~/.config/sway/config.d/autostart_applications:`

```
# cliphist
exec wl-paste --watch cliphist store
```

Then bind this to a command in sway:

`~/.config/sway/config.d/default:`

```
    # clipboard manager
    bindsym $mod+v exec cliphist list | rofi -dmenu | cliphist decode | wl-copy
```

Cheers!
