### ISSUE TITLE
cliphist ignores small entries

### ISSUE THREAD

**Issue by ftphikari** [sentriz/cliphist#17]
cliphist doesn't seem to store any text with 2 letters or less, for example it doesn't store `ab`, but stores emoji and japanese characters just fine.

**Comment by sentriz** [comment]
this was actually meant as a "feature" to not clutter the history with small useless entries 

https://github.com/sentriz/cliphist/blob/master/cliphist.go#L66-L68

but do you think it could be useful to copy small selections like that?

**Comment by ftphikari** [comment]
> but do you think it could be useful to copy small selections like that?

When storing only primary selection - maybe?? Very very maybe. When storing normal clipboard - no, it's not intuitive and i don't think it's useful. Sometimes i just want to copy and store ō symbol, you know.
