### ISSUE TITLE
delete item from list

### ISSUE THREAD

**Issue by Mathew-D** [sentriz/cliphist#18]
I am trying to get cliphist to delete an item in the list from a menu selection and I am hoping someone can help.
I have tried:
`cliphist list | rofi -dmenu | cliphist delete`
but it says: "please provide a delete query"  so instead I tried 
`cliphist list | rofi -dmenu > cliphist delete`
The command doesn't give an error but it doesn't remove the item.

Any help would be great.
Thanks.

**Comment by sentriz** [comment]
the `cliphist delete` is meant for manually searches. eg `$ cliphist delete password`

but I just added a command so this should work:

`cliphist list | rofi -dmenu | cliphist delete-stdin` which will decode the ID and delete that way instead

sorry the docs around cliphist are basically non-existent :)

**Comment by Mathew-D** [comment]
Can you do a release with this update please.

**Comment by sentriz** [comment]
Added
