### ISSUE TITLE
Consider to remove duplicates

### ISSUE THREAD

**Issue by Crandel** [sentriz/cliphist#2]
I was using clipman in Swaywm for a while, but I saw your project and decide to try it.

Unfortunately very quickly my bemenu list was full of duplicates(typically for my work). 

Is it possible to remove duplicates in output?

**Comment by sentriz** [comment]
yeah nice idea. now it will search backwards the most recent entries when storing, remove duplicates, and "move" the new input to the top when storing 👍

`$ go install go.senan.xyz/cliphist@master`

should get you the update

**Comment by Crandel** [comment]
Thank you!
