### ISSUE TITLE
[Feature Request] Snippet support

### ISSUE THREAD

**Issue by wakatara** [sentriz/cliphist#23]
It would be amazing if cliphist also provided the ability to have a separate db from the cliphist (sniphist?) that was somehow editable (if even only text at first) and allowed one to pull up and filter selections from both multiline text snippets, images etc... in rofi or dmenu. 

Basically, think of it as a saved, persistent clipboard of things you often copy-paste. Personally, I've got a heap of these in text like  ¯\\_(ツ)_/¯, gpg pub key, etc etc... (plus gif memes would be great as well... =] ).

thanks for considering it either way!

**Comment by sentriz** [comment]
cool idea. I  a simple approach to this on the cliphist side would just be setting the database path via an env var. for example, you could have workflows like

```shell
# store a new snippet from what's in your clipboard
$ CLIPHIST_DB_PATH="$XDG_DATA_HOME/cliphist-snippets" wl-paste | cliphist store

# copy a normal item
$ cliphist list | <dmenu> | cliphist decode | wl-copy

# copy a snippet item
$ CLIPHIST_DB_PATH="$XDG_DATA_HOME/cliphist-snippets" cliphist list | <dmenu> | cliphist decode | wl-copy
```

and ofc these would be bound to a key or script or whatever so as not to type stuff

thoughts?

**Comment by dogknowsnx** [comment]
> thoughts?

In combination I think it would make sense to have the ability to set the maximum number of entries, since a lot of the data will probably never be used/pasted again, e. g.  very large entries (default could still be 'unlimited').
