### ISSUE TITLE
[ HIGH PRIO BUG] cliphist interferes with wl-copy --paste-once

### ISSUE THREAD

**Issue by Zeioth** [sentriz/cliphist#25]
cliphist provokes this command to fail (returns No selection)

    echo test | wl-copy --paste-once
    wl-paste

When cliphist is stopped, the commands work as expected . 

This issue provoke some applications to not work correctly (swayshot).

See full discusion [here](https://github.com/bugaevc/wl-clipboard/issues/127).

**Comment by sentriz** [comment]
cliphist has no idea about wl-copy or wl-paste. but it does suggest from the docs to use wl-paste --watch cliphist store 


perhaps try asking the wl-clipboard guys if there is an issue with wl-paste --watch and wl-copy --paste-once

**Comment by Zeioth** [comment]
I did. I pasted you the link to [the discussion](https://github.com/bugaevc/wl-clipboard/issues/127).

**Comment by sentriz** [comment]
I don't see any mention of --watch in that thread. I would test it myself but I've not been doing much computer stuff recently

**Comment by Zeioth** [comment]
No worries, I just find the bug in manjaro-sway. Thank you so much for your help.

**Comment by Zeioth** [comment]
The issue is specificly with 

    wl-paste --watch cliphist store

Manjaro-sway autostarts this command on startup

```
exec {
    '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch cliphist store'
    '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch pkill -RTMIN+9 waybar'
}
```

**Comment by sentriz** [comment]
yes and the issue doesn't lie with cliphist, it could be any program in that `--watch` command. for example we could put `cat`

```shell
[senan@laptop ~]$ wl-paste --watch cat &
[1] 655855
[senan@laptop ~]$ echo hi | wl-copy --paste-once
[senan@laptop ~]$ hi        # printed from cat
[senan@laptop ~]$ wl-paste
No selection                # since cat already got it
```

that's why I think you should ask the wl-clipboard guys if there is a bug with `wl-paste --watch` and `wl-copy --paste-once` or maybe it's intended behaviour

**Comment by Zeioth** [comment]
Thank you for testing it @sentriz . Reaching wl-clipboard devs.
