### ISSUE TITLE
Support for rofi

### ISSUE THREAD

**Issue by fahimscirex** [sentriz/cliphist#29]
How do i use it with rofi?

**Comment by sentriz** [comment]
cliphist list can be piped to the stdin of any program, and cliphist decode reads an entry from stdin - outputting to stdout. so something like this should work:

`cliphist list | rofi -dmenu | cliphist decode | wl-copy`

**Comment by sentriz** [comment]
@asklow hm i think in that case (and assuming bash) you could do your script in two parts with `set -e`. so that the script exits when you don't select anything

```bash
#!/usr/bin/env bash

set -e

selection="$(cliphist list | rofi -dmenu)"
cliphist decode <<<"$selection" | wl-copy
```
