### ISSUE TITLE
Currently, would it be possible to limit list count to a specific number?

### ISSUE THREAD

**Issue by akhiljalagam** [sentriz/cliphist#30]
previously, I used this to limit history to 1000 lines
`clipman pick --max-items=1000 -t rofi`  

But, I don't find any option to control history count in cliphist  
something like this would be very useful  
`cliphist list --max-items=1000 | rofi -dmenu | cliphist decode | wl-copy`

**Comment by sentriz** [comment]
what about about adding a `tail -n 1000` to the pipeline before the rofi step? I like to keep the scope of cliphist small

**Comment by akhiljalagam** [comment]
What is the maximum limit on the items stored by cliphist?

**Comment by sentriz** [comment]
it's 750 items at the moment

**Comment by sentriz** [comment]
this is now configurable :+1: eg `cliphist -max-items 750 store`

**Comment by w-jablonski** [comment]
FWIW, the above `cliphist store -max-items 100` doesn't seem to work in this order, at least when put in a longer expression. However, this expression `exec wl-paste --type text --watch cliphist -max-items 100 store` works. Thanks.

**Comment by sentriz** [comment]
ah yes, thanks @w-jablonski updated the comment
