### ISSUE TITLE
Wipe doesn't work?

### ISSUE THREAD

**Issue by ChristianWSmith** [sentriz/cliphist#32]
Figured a picture is worth 1000 words...
![image](https://user-images.githubusercontent.com/56562906/216617643-4397895c-1025-4ee9-93ab-0e0c19b885fa.png)

**Comment by sentriz** [comment]
ah I think I only added wipe yesterday so it's unreleased and not in v0.3.1

if you install from source it should be there 

    go install go.senan.xyz/cliphist@latest


or else youd have to wait until the next version 😔 thanks !

**Comment by ChristianWSmith** [comment]
ahh understood, kudos on the project by the way!

**Comment by sentriz** [comment]
thanks :) in the meantime a simple `rm $XDG_CACHE_HOME/cliphist/db` will do the same thing

**Comment by ChristianWSmith** [comment]
thanks fam!
