### ISSUE TITLE
Is there a way to ONLY copies images from browsers, and not the html data?

### ISSUE THREAD

**Issue by WasteOfO2** [sentriz/cliphist#33]
It is pretty annoying to have both html data and the raw image when i copy the image from my browser, is there a way i can possibly blacklist or get rid of that html data entirely and only copy the raw image?

**Comment by sentriz** [comment]
what if you run two instances of wl-paste --watch. one with `--type text` another with `--type image`.  then I think you should only end up with either pure text (no html data) or raw images in your clipboard

**Comment by WasteOfO2** [comment]
thx that helped
