### ISSUE TITLE
Max history

### ISSUE THREAD

**Issue by Chr1s70ph** [sentriz/cliphist#34]
Instead of having an infinite history, an option to toggle a max length would be pretty nice.
If that certain length is reached, the last entry is cleared to save space.

It should be relatively easy, since 'cliphist delete' already exists.

Is that something you would consider implementing?

**Comment by Chr1s70ph** [comment]
Closed with df85b70

**Comment by ImnotEdMateo** [comment]
and how can I use it?

**Comment by sentriz** [comment]
@ImnotEdMateo you can do `cliphist -max-items 2000 store`. alternatively, configure with an env var such as CLIPHIST_MAX_ITEMS=2000, or a config file with `max-items 2000` in $XDG_CONFIG_HOME/cliphist/config

full list of options are 

```
  -config-path
    overwrite config path to use instead of cli flags
  -db-path
    path to db
  -max-dedupe-search (default 100)
    maximum number of last items to look through when finding duplicates
  -max-items (default 750)
    maximum number of items to store
  -preview-width (default 100)
    maximum number of characters to preview
```

env var format is CLIPHIST_<flagname_uppercase>

config file format is `<flagname> <value>`

more info here https://pkg.go.dev/go.senan.xyz/flagconf#hdr-usage
