### ISSUE TITLE
[Feature request] Reversed "cliphist list" to show newest at bottom

### ISSUE THREAD

**Issue by w-jablonski** [sentriz/cliphist#38]
I simply run `cliphist list` in terminal whenever I need to access some previously copied short text. But currently the newest items are way above, requiring a scroll. Maybe it wouldn't be a problem to implement an alternative "list", which would show newest entries at the bottom?
Thanks!

**Comment by sentriz** [comment]
can you just pipe into `tac`? eg `cliphist list | tac | dmenu`?

**Comment by w-jablonski** [comment]
Sorry, didn't know about `tac`!
