### ISSUE TITLE
[Feature Request] Access the previous-to-last clipboard entry

### ISSUE THREAD

**Issue by w-jablonski** [sentriz/cliphist#45]
Hi again. Can we have (or maybe we already have?) a way to paste the previous (or prior to last) clipboard entry, without launching the picker? I have little knowledge of how the clipboard works, but I guess it would involve piping this item to `wl-paste`?... Thank you!

**Comment by sentriz** [comment]
sure, to copy the second last item to your clipboard, you could do

`cliphist list | sed '2q;d' | cliphist decode | wl-copy`

but this will only copy to the clipboard and make it availible to wl-paste. it won't psysically paste for you (maybe something like wtype can do that but i've never tried it)

does that help?

**Comment by w-jablonski** [comment]
Thank you, again, for you help!
