### ISSUE TITLE
wl-paste / cliphist does not register new clipboard entries after suspend

### ISSUE THREAD

**Issue by hashworks** [sentriz/cliphist#48]
I run cliphist as a systemd user service started after a sway session target:

```
[Unit]
Description=wayland clipboard manager
BindsTo=sway-session.target

[Service]
Type=simple
ExecStart=/usr/bin/wl-paste --watch cliphist store

[Install]
WantedBy=sway-session.target
```

When I suspend my laptop and resume it later, cliphist (or wl-paste?) will not register new clipboard entries until I restart the unit.

Is this known behaviour of wl-paste? Should one configure systemd to restart it after suspend?

**Comment by hashworks** [comment]
Hm, now that I'm trying to debug it I can't reproduce it anymore :/

**Comment by sentriz** [comment]
hard to tell if this is a cliphist issue . does the same issue happen with something like `wl-paste --watch tee /tmp/test`. as in, items stop getting written to /tmp/test after suspend?

**Comment by hashworks** [comment]
To test this, I'll be running the following alongside cliphist.
```
[Unit]
Description=wayland clipboard manager test
BindsTo=sway-session.target

[Service]
Restart=always
Type=simple
ExecStart=/usr/bin/wl-paste --watch sh -c 'echo -n "$(date -Is): " >> /run/user/1000/wl-paste-test; cat >> /run/user/1000/wl-paste-test; echo >> /run/user/1000/wl-paste-test'

[Install]
WantedBy=sway-session.target
```

**Comment by sentriz** [comment]
how did that go?
