### ISSUE TITLE
Is it possible to specify the location of the db?

### ISSUE THREAD

**Issue by kevenwyld** [sentriz/cliphist#49]
I'd like the db to live in memory, rather than needing to worry about wiping it.  Is it possible to specify the location of the DB with either an env var or an option?

If not maybe you would be open to adding this as a feature?

Either way thank you for this tool!

**Comment by sentriz** [comment]
hey, yes you can set a specfic `XDG_CONFIG_HOME` just for cliphist. 


eg with the ram tmpfs `$ XDG_CONFIG_HOME=/tmp cliphist store`
