### ISSUE TITLE
copying image from firefox also copies html and some gibberish

### ISSUE THREAD

**Issue by ugly-custard** [sentriz/cliphist#53]
I've recently switched to wayland, Hyprland, on arch linux so I'm still looking for x alternative apps and this felt very similar to what I used on x, my fork of clipmenu to support images.
Except, problems in copying images :(

I'm using the fix from #33 (and on the readme)
```
wl-paste --type text --watch cliphist store
wl-paste --type image --watch cliphist store
```

when copying an image, there's the html, the actual image, and some gibberish in the history:
```
❯ cliphist list 
157	ftypavifavifmif1miafMA1Bmeta(hdlrpictlibavifpitm
156	binary data image/png
155	<meta http-equiv="content-type" content="text/html; charset=utf-8"><img id="image" class="fit-width"
```

With only `wl-paste --type image --watch cliphist store`  there's no gibberish but sometimes there's an extra image (jpeg here) entry, which I can't paste anywhere:
```
❯ cliphist list
167	binary data image/jpeg
166	binary data image/png
```

My suspect for the gibberish is copying the same image again, its random but very likely.
It also happens when I copy an image for the first time so not so sure, but it is more likely for it to happen on a second copy.

So my question is, same as issue #33, can I only copy the image and not the html? with text support as well while not copying images...
and, well, can I not get that gibberish? I do not know the source of it so if someone could replicate it, it would be nice to know.

Should I have instead commented on the closed #33? But there's the gibberish too.
I'm new to collaborating on github so dunno. You can close this issue and I'll comment there instead if that's the case :)

**Comment by sentriz** [comment]
that is very strange. what happens when you try "select" one of those gibberish linesm - 157 in your example, and pipe it into `file`? eg `printf "157\t" | cliphist decode | file`

what does it say

**Comment by ugly-custard** [comment]
```
❯ cliphist list
409	BM6(R`?>>>>===??????>
407	binary data image/png
403	0,0
400	<meta http-equiv="content-type" content="text/html; charset=utf-8"><img id="image" class="fit-width"
```
Note: The position of gibberish ```BM6(R`?>>>>===??????>``` changed since I selected it again to paste it after running the below command.

I can't pipe it into file, so I saved it as a new file and then used the file command instead.
```printf "402\t" | cliphist decode > newfile``` and then ```file newfile```.
The result of which was:
```newfile: PC bitmap, Windows 3.x format, 850 x 660 x 24, image size 1684320, cbSize 1684374, bits offset 54```

I still can't paste it tho, but I can paste the actual ```binary data image/png``` image.

Also note the extra `0,0` entry (it only shows as `0` in rofi) that randomly appears without me copying it explicitly (possibly part of the gibberish as well)
Using the file command on it gives `data`, which I still can't paste anywhere, neither can I select it with rofi for some reason? The rofi window goes away but the 0 entry stays at its position.

This all seems very weird to me, and can only hope someone can replicate it.
I should try reinstalling these packages again.

**Comment by sentriz** [comment]
can you try install cliphist from source? and also is this the case with all images in Firefox or just some? can you send a link to an image

**Comment by ugly-custard** [comment]
Can you try it with this post? I've been met with the gibberish entry 4/5 times [(it's sfw anime post on danbooru)](https://danbooru.donmai.us/posts/6524015)

I've also tried with the wallpapers on wallhaven.cc, where I encountered only the `0,0` entry, only once after many attempts.

**Comment by sentriz** [comment]
hm nope i can't reproduce it. i get two entries as expected and no gibberish. maybe you have some extra processes on your system doing something weird? `ps aux | grep -E "(wl|clip|paste)"`

**Comment by ugly-custard** [comment]
Indeed! I also had `wl-clip-persist` running, and it's cuz of that!
I killed the process and didn't get any gibberish, but starting it again did
Thanks for your time!
I will close the issue now
