### ISSUE TITLE
Type video Support?

### ISSUE THREAD

**Issue by semi710** [sentriz/cliphist#56]
Is it possible to have video type support?

**Comment by sentriz** [comment]
it's already possible, for example

```
$ wl-paste -t video -w cliphist store
$ wl-copy <example.mp4
$ cliphist list | head -n 1
<some video data>
```

you can copy multiple videos and reselect them later (though you might need xdg-utils installed for this to work nicely) 

that said, i don't actually recommend this. if you have large video files, you are duplicating them into the cliphist database
