### ISSUE TITLE
[Enhancement] Display only the n-th column of an output

### ISSUE THREAD

**Issue by pescepalla** [sentriz/cliphist#57]
As in rofi's `-display-columns _n_` option?

Example: `cliphist list | tofi -display-columns 2 | cliphist decode | wl-copy` would only show me the second column of the `cliphist` output. This is useful because the first column is a number that has little utility for the human user.

**Comment by pescepalla** [comment]
I migrated from cliphist to clipman, which does not present this issue.

**Comment by sentriz** [comment]
there's a section in the readme about this

**Comment by pescepalla** [comment]
Sorry, I had meant to publish this on `tofi`'s github. I read the readme, but it seems like only `rofi` and `fzf` can reliablyt pull the trick of removing the number and the weird separator.
