### ISSUE TITLE
sync both clipboard 

### ISSUE THREAD

**Issue by kristoferus75** [sentriz/cliphist#59]
hi !

corrently i use x11 with dwm to sync both clipboards:

```
autocutsel -fork -selection CLIPBOARD &
autocutsel -fork -selection PRIMARY &
```

Is this possible also with cliphist in wayland ?

currently i use this line to start cliphist:

`wl-paste --watch cliphist store &`

to show clipboard i use this line:

`cliphist list | rofi -dmenu -p Clipboard | cliphist decode | wl-copy`

thanks !

**Comment by sentriz** [comment]
hm maybe try

wl-paste --watch cliphist store &
wl-paste --primary --watch cliphist store &
