### ISSUE TITLE
[Feature Request] Ability to delete a list or range of entries

### ISSUE THREAD

**Issue by ChanceHarrison** [sentriz/cliphist#63]
Use case: I would like to be able to delete many entries in `cliphist` without wiping all the entries. The entries I want to delete are not  related in their contents, so `delete-query` isn't suitable for the job. This would be particularly useful for use with pickers that support selecting multiple items.

Potential implementations:
- Modify `delete` so that when it takes `os.Stdin`, iterate over the lines (assuming each entry one wants to delete is on a newline, which is at least [how `rofi` returns row selections](https://github.com/davatorium/rofi/blob/next/doc/rofi-dmenu.5.markdown#basic-concept)) and try to delete each (i.e., attempt ID extraction, go from there). One can probably batch the database operations or at least reuse the same session/connection/whatever?
- Provide a subcommand that takes a starting entry and and ending entry and deletes each entry between start and end inclusive.
  - I'm not sure how this would integrate with a picker, but it could be useful for direct use on the command line 

Alternatives:
- Shell script around it
- Save what you want out of the clipboard, then you can just wipe it

Is there any interest in contributions that would satisfy this use-case? If so, would you prefer any particular implementations? Do you think this functionality would be a good addition to the core of `cliphist` (i.e., not a script/contrib)?

Thanks for your work and time <3

**Comment by sentriz** [comment]
hm yeah I wouldn't be opposed to the delete command receiving a stream of newline delimited rows to delete. if its input is the output of cliphist list, then we can be sure that one line is one entry

so 
`cliphist list | pick N lines | cliphist delete`
seems reasonable to me
