### ISSUE TITLE
cliphist list number of truncated characters cli option

### ISSUE THREAD

**Issue by ed7ed** [sentriz/cliphist#64]
As a user of `bemenu` I wish to fit my width screen fully when preview history using `cliphist list` command and let bemenu truncate on its own if needed.  Something like `cliphist list -w 999`. Now the value is hardcoded and equal to 100.

What do you think?

**Comment by sentriz** [comment]
I see, you want more than 100 chars preview ?

**Comment by ed7ed** [comment]
Exactly, maybe it is good having 100 characters per a line is an default option and if the user provides an option use user's value instead.

**Comment by sentriz** [comment]
fixed by #88
