### ISSUE TITLE
with dmenu, square icon next to history number

### ISSUE THREAD

**Issue by bdantas** [sentriz/cliphist#65]
I'm using cliphist with dmenu and functionally it is perfect. I just have one cosmetic issue, which is a little square that appears to the right of the history item number, as seen in this [screenshot](https://gnuser.ddns.net/public/screenshot001.jpg). 
 
I've tried different fonts (as in `dmenu -fn Hack`) and no luck getting rid of the square. Do you know what that square is doing there, and if it is possible to remove it?

**Comment by sentriz** [comment]
that is the tab character. maybe your font doesn't render it properly? (you could also try an alternative wayland picker like wofi or fuzzel) 

maybe you could just turn it into a space before it gets to dmenu, and convert it back before it gets to cliphist decode (cliphist decode needs the tab)

`$ cliphist list | sed -E "s/^([0-9]+)\t/\1 /" | dmenu | sed -E "s/^([0-9]+) /\1\t/" | cliphist decode | wl-copy`

bit of a hack though. would be better to sort the font out or use a different picker

**Comment by bdantas** [comment]
Hi sentriz. Yes, I can confirm it is a tab. Your suggested solution fixes the cosmetic issue but breaks functionality: Choosing an item results in empty clipboard. Maybe cliphist expected the tab to be there?
 
I agree finding a font that can deal with the tab is a better solution. I'll play around until I find one. Many thanks. Happy hacking!

**Comment by sentriz** [comment]
i agree :+1: 

> Maybe cliphist expected the tab to be there?

the second sed command should reverse the operation, replacing the tab with a char again. maybe i got the command wrong though

**Comment by bdantas** [comment]
Oops, my bad. I missed the second `sed` in the pipeline. Yes, what you suggested fixes the cosmetic issue and works just fine. Thanks again :)
