### ISSUE TITLE
Sway Wofi Launcher Potential Issue empty no items

### ISSUE THREAD

**Issue by pjkaufman** [sentriz/cliphist#67]
Hey. I have been looking for a clipboard manager for Wayland and noticed this project. It looks great! Though I have been having some trouble getting it to work right in my Sway config. I am guessing this is operator error on my part, but I wanted to reach out just to make sure.

I installed `cliphist` via Go.
My Sway config then had the following added
```
# Clipboard
bindsym $mod+Shift+v exec "cliphist list | wofi --dmenu | cliphist decode | wl-copy"
…
exec --no-startup-id swaymsg 'workspace 1; wl-paste --type text --watch cliphist store &' #Stores only text data
exec --no-startup-id swaymsg 'workspace 1; wl-paste --type image --watch cliphist store &' #Stores only image data
```

However whenever I do `$mod+Shift+v` I get the following screen even when the clipboard has values:
![image](https://github.com/sentriz/cliphist/assets/29898683/d7b88d79-6e7f-418f-8271-ff99b36dd60c)

But when I run `cliphist list | wofi --dmenu | cliphist decode | wl-copy` from a terminal I get the following: 
![image](https://github.com/sentriz/cliphist/assets/29898683/7d28b04d-ef80-4c16-a3b4-a45d61b38aff)

Any ideas what I might be doing wrong?

**Comment by sentriz** [comment]
is it possible that XDG_CACHE_HOME is configured differently between the shell sway is launched from, and your normal desktop shell? try `swaymsg exec "notify-send $XDG_CACHE_HOME"`

**Comment by sentriz** [comment]
if it's different to your desktop shell env, i'd recommend setting it at a higher level. for example in your login shell rc, or .profile, or .config/environment.d etc depending on your distro

**Comment by pjkaufman** [comment]
Thanks for the fast response! That looks like the problem. I guess I need to figure out why my bashrc exports are not being used.

The xdg cache is not set in Sway, but it is set in my bashrc.

**Comment by sentriz** [comment]
is bash your login shell? looks like it will never be set for non interactive :grin: try moving it up https://github.com/pjkaufman/dotfiles/blob/master/bash/bashrc#L14

**Comment by pjkaufman** [comment]
I am not sure if bash is my login shell, but moving the non-interactive check after the exports in the file did not seem to fix things.

**Comment by pjkaufman** [comment]
I use the Pop OS! login screen, so bash may not be considered to be my login shell. Is reloading sway enough to reload its variables or do I need to log out and back in in order to refresh those env vars? If the latter, I tested it wrong this morning.

**Comment by sentriz** [comment]
maybe try put them in .profile then. you may need to reboot or restart your display manager. not sure how those work

**Comment by pjkaufman** [comment]
Gotcha. I will tinker with this and see if I can get it set for Sway. Is there a default location that cliphist puts its cache if the xdg cache variable is not set?

**Comment by pjkaufman** [comment]
Ok. So I fixed the xdg variable not being set, but I still see the same problem arising. Are there any other things I should check before manually building a version of `cliphist` to print out debug info about where it is looking for things?

**Comment by pjkaufman** [comment]
I think the remaining issue is a path issue. I am pretty sure what is happening is the go installed file is not in the path causing cliphist to fail to run. Let me try to fix that and if that is not the issue I will see about getting help from there.

**Comment by pjkaufman** [comment]
The issue was with my setup. We should be good to close this issue. For those wondering, I had to do the following to get my login manager to properly fix things:
- First find out what Pop OS! uses as its login manager
  - This is gdm
- Then I had to figure out how to set variables for it
  - This is explained well by https://unix.stackexchange.com/a/326161
  - The gist of it is that I needed to add the proper env variables to a `*.env` file under `/usr/share/gdm/env.d/`
    - Changes to this file require a reboot to take effect
- Then I needed to make sure to set my xdg variables the same as what I use in the shell and my path to the go files in my path for gdm
Once all of that was done, it worked. You probably do not need to add the path to where Go files are installed if you use an installation method other than Go.

Thanks for helping me with this @sentriz !

Edit:

An alternate method:
- Add an entry under `~/.config/environment.d`
- The file should be called `sway.conf`
- Add env variables there in the format `VAR_NAME=VAL` and then reboot your computer
These two methods seem to work for me. I prefer the `environment.d` route
