### ISSUE TITLE
Copying images doesn't seem to work

### ISSUE THREAD

**Issue by Kommynct** [sentriz/cliphist#69]
When I take a screenshot and attempt to go to it with "`cliphist list | tofi | cliphist decode | wl-copy`" wl-paste reports that it's text/plain, I can't figure out why

```
wl-paste -l  
text/plain
text/plain;charset=utf-8
TEXT
STRING
UTF8_STRINGh
```

I have 	 
```
exec wl-paste --watch cliphist store
exec wl-paste --type image --watch cliphist store
```
in my sway config, any advice?

**Comment by sentriz** [comment]
do you have xdg-utils installed?

**Comment by Kommynct** [comment]
Ah, I use xdg-utils-handlr, that could definitely be the problem, i'll test that later, sorry, I forgot about that.

edit: yup that's it

edit2: and handlr's dead anyway, so, not worth trying to support in any way regardless, closing
