### ISSUE TITLE
[SUGGESTION] - Release chiphist in openSUSE Build Service

### ISSUE THREAD

**Issue by RiQuY** [sentriz/cliphist#72]
I suggest releasing this package for openSUSE Tumbleweed, I don't think there will be any dependencies problems because openSUSE Tumbleweed is a rolling release distro an it offers a similar service like the AUR of Arch Linux but called openSUSE Build Service.

 If it sounds interesing to you maybe is worth taking a look at it. https://build.opensuse.org/

**Comment by sentriz** [comment]
hey I don't use opensuse so I have no interest in that. but feel free to create/maintain a cliphist package yourself - that would be cool

there are lots: https://repology.org/project/cliphist/versions
