### ISSUE TITLE
Multi-line content

### ISSUE THREAD

**Issue by Acumane** [sentriz/cliphist#73]
While rofi doesn't support variable-height elements, a fixed value can be specified with `-eh`. It would be really nice if multi-line content took advantage of this.

This could be implemented as a `dmenu` using `-drun-display-format "{<row1>}$'\n'{<row2>}"`, but `cliphist list` probably(?) needs to be decoded first

**Comment by sentriz** [comment]
i think this is out of scope for the core of cliphist (but reopen if you think not)

check the cliphist fzf in contrib/ for an example of show full multi line previews in the picker
