### ISSUE TITLE
Add vendor directory

### ISSUE THREAD

**Issue by henri-gasc** [sentriz/cliphist#74]
Good morning? evening? I don't really know.

Anyway, Could it be possible to add the vendor directory either in the the git itself or in a tarball for all release ?
I am asking because over on Gentoo, we need to have the Go dependencies bundled with the source. As such I created [this](https://github.com/henri-gasc/cliphist) repo with the only change being adding vendor and removing .github.

If you can not do it, it's no bother.

**Comment by sentriz** [comment]
hm i dont know anything about gentoo. but how does a Go project like fzf for example have a gentoo package? seemingly they dont vendor their dependencies  

https://github.com/junegunn/fzf
https://packages.gentoo.org/packages/app-shells/fzf

**Comment by henri-gasc** [comment]
The writer/maintainer of the ebuild (for fzf-0.44.0 it's Sam James) keep the dependencies in a tarball that follows the release cycle and add it to the ebuild [line 18](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-shells/fzf/fzf-0.44.0.ebuild#n18).

It's not something hard to do, I just feel like I am "stealing" your work by using my own repo and not yours

**Comment by sentriz** [comment]
ahh i see. i think in this case i would not add a vendor/ pkg to the repo. i don't think it's standard practise really in the Go world. unless maybe for big companies - not sure

but any if you make an offical Gentoo package, big thanks!
