### ISSUE TITLE
How to quit picker without clearing clipboard ?

### ISSUE THREAD

**Issue by foxjaw** [sentriz/cliphist#75]
`cliphist list | <picker> --dmenu | cliphist decode | wl-copy` usually invokes the picker & escaping it clears the clipboard. Is there anyway I can modify above command so that clipboard does not clear on quitting the picker without selecting the last clip ?

**Comment by sentriz** [comment]
sure, you can split the pipeline in two

https://github.com/sentriz/dotfiles/blob/master/conf_extra/.local/bin/dmenu-menus/dmenu-clipboard

**Comment by sentriz** [comment]
https://github.com/sentriz/cliphist/issues/29#issuecomment-1336499636

**Comment by sentriz** [comment]
just `echo "$selection" | cliphist decode`
