### ISSUE TITLE
won't preserve clipboard after copy source is closed

### ISSUE THREAD

**Issue by liaminventions** [sentriz/cliphist#77]
cliphist won't preserve the clipboard after the copy source is closed unless the picker is run

for example, I copied text from Brave Browser, and then closed it, and tried to paste, and no data was pasted.
it works if I open the picker first though...

am I just launching it wrong or something or is this a new feature?

i launch it like this:
```
wl-paste --watch cliphist store
```

**Comment by sentriz** [comment]
that's just a feature of wayland i believe. you could try a project like wl-clip-persist to fix it. apparently it works alongside cliphist

**Comment by liaminventions** [comment]
> that's just a feature of wayland i believe. you could try a project like wl-clip-persist to fix it. apparently it works alongside cliphist

thanks! I added `wl-clip-persist --clipboard both` and it worked perfectly!

**Comment by liaminventions** [comment]
quick update: I ended up using this command:

> wl-clip-persist --clipboard regular --all-mime-type-regex '(?i)^(?!image/x-inkscape-svg).+'

from here: https://github.com/Linus789/wl-clip-persist/issues/7

**Comment by Rabcor** [comment]
I've had problems with wl-clip-persist too, so I just solved it by creating a script for clipboard persistence using cliphist

```bash
#!/bin/sh

previous="$(cliphist list | head -1 | awk '{$1=null; print $0}')"

cliphist store

current="$(cliphist list | head -1 | awk '{$1=null; print $0}')"

if [ "$current" != "$previous" ]; then
	cliphist list | head -1 | cliphist decode | wl-copy
fi
```

and I just invoke it like this (where cliphist-persist is the script name)
`wl-paste --type text --watch cliphist-persist `
