### ISSUE TITLE
Copying Image from browser comes with HTML and Image

### ISSUE THREAD

**Issue by Paulo-B** [sentriz/cliphist#81]
I followed, as mentioned in #33 two instances of wl-paste. This is the configuration that I have in Sway:

```
exec_always {
  pkill wl-paste
  wl-paste --type image -p --watch $clipboardmanager store
  wl-paste --type text -p --watch $clipboardmanager store 
}
```
And still I have the HTML and the image both copied to the clipboard.

**Comment by sentriz** [comment]
that's just a side effect of wl-paste -t text for images. I would recommend just filtering it out in your pipeline after cliphist list

**Comment by danielwerg** [comment]
haven't tested thoroughly but here is workaround: 

```sh
wl-paste --type image --watch bash -c "cliphist store && sleep .1 && cliphist-clear-images-meta-tag"
```

`cliphist-clear-images-meta-tag`:

```sh
#!/bin/bash

cliphist -preview-width 1000 list | grep --fixed-strings '<meta http-equiv="content-type" content="text/html; charset=utf-8"><img ' | awk -F'\t' '{print $1}' | cliphist delete
```

**Comment by sentriz** [comment]
you can just `cliphist delete-query '<meta http-equiv="content-type" content="text/html; charset=utf-8"><img '`
