### ISSUE TITLE
Fzf now support sixel

### ISSUE THREAD

**Issue by semi710** [sentriz/cliphist#84]
is it possible to have image preview in that?

**Comment by sentriz** [comment]
sure, try running this https://github.com/sentriz/cliphist/commit/54f1c054d2610a9bf50fb2061f535ad555837abd

(with chafa installed)

**Comment by semi710** [comment]
> sure, try running this [54f1c05](https://github.com/sentriz/cliphist/commit/54f1c054d2610a9bf50fb2061f535ad555837abd)
> 
> (with chafa installed)

getting this error
```bash
extracting id: converting id: strconv.Atoi: parsing "\n": invalid syntax
```

**Comment by sentriz** [comment]
oh i had my personal version commited. try this https://github.com/sentriz/cliphist/blob/master/contrib/cliphist-fzf-sixel

**Comment by semi710** [comment]
works perfectly fine.

**Comment by sentriz** [comment]
youre welcome
