### ISSUE TITLE
Clear Database on shutdown / configurable path to db

### ISSUE THREAD

**Issue by dryBoneMarrow** [sentriz/cliphist#91]
It would be nice to have the option to clear the database at shutdown or to have a configurable path for the db (so one could place it in /tmp).

**Comment by dryBoneMarrow** [comment]
It is also possible to make a tmpfs (which is stored in ram and hence cleared on shutdown), like so (in `/etc/fstab`):
`tmpfs /home/username/.cache/cliphist/ tmpfs rw,nodev,nosuid,nofail,x-systemd.device-timeout=5
`
This could be added to the readme

**Comment by sentriz** [comment]
thanks for the suggestion

though clearing the db on shutdown is out of scope since the cliphist is supervised by wl-clipboard

**Comment by w-jablonski** [comment]
Thanks. So regarding a configurable path for the db, is it possible? And would something like the following work? 
> exec XDG_CACHE_HOME="$HOME/my_directory" wl-paste --watch cliphist store

Thanks for your time.

**Comment by sentriz** [comment]
yes that should work fine :+1:

**Comment by w-jablonski** [comment]
This actually doesn't work. Specifically, this line works when executed in terminal:

>wl-paste --type text --watch cliphist -max-items 100 store

But the below one doesn't:

>XDG_CACHE_HOME="$HOME/D/X/run" wl-paste --type text --watch cliphist -max-items 100 store

It still creates a folder in $HOME/.cache and the file at $HOME/D/X/run/cliphist/db is empty.

**Comment by sentriz** [comment]
seems to work for me

![image](https://github.com/sentriz/cliphist/assets/6832539/27290071-5b0e-4e94-8f76-9ad4a7f78048)

**Comment by w-jablonski** [comment]
Thanks, I missed the other half there.

So I can get it to work using:
In Sway config: 
>exec "env XDG_CACHE_HOME=$HOME/D/X/run wl-paste --type text --watch cliphist -max-items 100 store"

Then in terminal: 
>env XDG_CACHE_HOME="$HOME/D/X/run" cliphist list | fzf --layout=reverse --no-info | env XDG_CACHE_HOME="$HOME/D/X/run" cliphist decode | wl-copy

But strangely, if I put the second half in a `script.sh` and run something like `foot script.sh` then everything works fine **except** when I select an old entry it doesn't move to the top of the list - even though it copies to clipboard correctly...

Any advice on this? And thanks for your help anyway.

**Comment by sentriz** [comment]
@w-jablonski if you build form source, i just made the db path configureable with a flag

alternatively, you can change any flag with an env var or config file.
for example `env CLIPHIST_DB_PATH=$HOME/D/X/run/cliphist`

---

or instead create a ~/.config/cliphist/config which looks like:

```
db-path $HOME/D/X/run/cliphist-db
max-items 100
```

then you can just use `cliphist` anywhere without an env prefix or -max-items param

**Comment by w-jablonski** [comment]
Sadly, I need to wait for new release or an AUR package.
Thanks!
