### ISSUE TITLE
How to configure cliphist to save in history the selected text with mouse?

### ISSUE THREAD

**Issue by jetm** [sentriz/cliphist#92]
Start using Hyprland and coming from KDE. In KDE there is Klipper as a clipboard manager; it allows you to copy in the clipboard history any text after being selected with the mouse. It's a nice feature because it saves pressing the Ctrl+C keys. This kind of behavior can be configured in Kitty, but I have been unable to make it work outside of the terminal. I have tried:
```
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard both
```

I can confirm the previous settings only copy the text when it's is selected with the keyboard. It doesn't work copy the text when is selected with the mouse.

- Do I am missing something in my configuration? 

- Is this an issue in cliphist or wl-paste?

- How could I know where to identify is the problem? Anything else I would need to do to find out where the problem is?

I am using `cliphist v0.5.0` in Arch Linux and `Hyprland v0.37.0`.

**Comment by sentriz** [comment]
can you try `wl-paste --primary --type text --watch X`
