### ISSUE TITLE
Missing version tag

### ISSUE THREAD

**Issue by alerque** [sentriz/cliphist#94]
I've got some folks flagging the [Arch Linux package](https://archlinux.org/packages/extra/x86_64/cliphist/) as out of date based on dec2628e16fca7a46347345b32858f79907fcd92, but I don't see a release tag. Did you forget to push a tag to the repository? Is that intended for public consumption? Was #89 supposed to be merged?

Also whats the deal with the newer but lower v0.1.2 tag? What should a disto even be packaging here?

**Comment by sentriz** [comment]
hey, that's just a pull request which is getting the next release ready. the release does not exist yet, and wont until the PR is merged. once the PR is merged, a release is created with the changelog that you see in the PR body 

it's based on release-please: https://github.com/google-github-actions/release-please-action

so sorry for the confusion, you can ignore the out of date flag. v0.5.0 is the latest

**Comment by sentriz** [comment]
that's really strange , i've neer seen that 0.1.2 before. I've deleted it
