### ISSUE TITLE
Sync with KDE Connect?

### ISSUE THREAD

**Issue by semi710** [sentriz/cliphist#96]
Is there any possibility that Content from Mobile clipboard when shared is saved to cliphist?

**Comment by sentriz** [comment]
this should already be the case, if KDE connecting is populating the system clipboard. have you trie it?

**Comment by semi710** [comment]
Aah I have to manually send the Clipboard there is no live sync like it happens from system to mobile.

**Comment by sentriz** [comment]
I'm not entirely familiar with KDE connect. but I imagine for mobile to desktop syncing , when you make a copy on your phone its sent to the desktop daemon. the desktop will copy that to the system clipboard using Wayland protocols. if that's the case then cliphist should work fine
